version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_net

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: php
    container_name: symfony_php
    env_file:
      - ./docker/php/.env
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
    networks:
      - symfony_net

  php-messenger:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: php-messenger
    container_name: symfony_php_messenger
    restart: unless-stopped
    env_file:
      - ./docker/php/.env
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
    networks:
      - symfony_net

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge
