# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    db.host: '%env(string:DATABASE_HOST)%'
    db.port: '%env(string:DATABASE_PORT)%'
    db.name: '%env(string:DATABASE_NAME)%'
    db.user: '%env(string:DATABASE_USER)%'
    db.pass: '%env(string:DATABASE_PASS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    _instanceof:
        App\PaymentRule\PaymentRuleInterface:
            tags: ['app.payment_rule']

    App\PaymentRule\PaymentRuleFactory:
        arguments:
            $rules: !tagged_iterator app.payment_rule

    App\PaymentRule\JuneRule:
        tags: ['app.payment_rule']
    
    App\PaymentRule\MonthToMonthRule:
        tags: ['app.payment_rule']
    
    App\PaymentRule\DelayMonthRule:
        tags: ['app.payment_rule']
    
    App\PaymentRule\OnePaymentRule:
        tags: ['app.payment_rule']
